config-version = 2
# macOS のユーザーセッションへのログイン後に実行するコマンドを追加できます
# 'after-login-command' を有効にするには、'start-at-login' を 'true' にする必要があります
# 使用可能なコマンド: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# AeroSpace の起動後に実行するコマンドを追加できます
# 'after-startup-command' は 'after-login-command' の後に実行されます
# 使用可能なコマンド: https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# ログイン時に AeroSpace を起動
start-at-login = true

# 正規化の設定。詳細: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# 詳細: https://nikitabobko.github.io/AeroSpace/guide#layouts
# 'accordion-padding' はアコーディオンレイアウトの余白サイズを指定します
# 0 にすると余白を無効にできます
accordion-padding = 0

# 指定できる値: tiles|accordion
default-root-container-layout = 'tiles'

# 指定できる値: horizontal|vertical|auto
# 'auto' の場合、横長のモニター（幅が高さより大きい）は横向き、
#           縦長のモニター（高さが幅より大きい）は縦向きになります
default-root-container-orientation = 'auto'

# 指定できる値: (qwerty|dvorak)
# 詳細: https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# フォーカス中のモニターが変わると、マウスカーソルも追従します
# この動作が不要な場合は、設定からこの項目を削除してください
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# ウィンドウ間（inner-*）およびモニター端との間（outer-*）の余白です
# 指定できる値:
# - 固定値:       gaps.outer.top = 8
# - モニター別:   gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 この例では、該当するモニターがない場合の既定値は 24 です
# モニターのパターンには 'workspace-to-monitor-force-assignment' と同じ形式を使います
# 詳細: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

# 'main' バインドモードの宣言
# 詳細: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' バインドモードは必ず定義してください
[mode.main.binding]

# 使用できるキー:
# - 英字:               a, b, c, ..., z
# - 数字:               0, 1, 2, ..., 9
# - テンキーの数字:     keypad0, keypad1, keypad2, ..., keypad9
# - ファンクションキー: f1, f2, ..., f20
# - 特殊キー:           minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                       leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - テンキーの特殊キー: keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                       keypadMinus, keypadMultiply, keypadPlus
# - 矢印キー:           left, down, up, right

# 使用できる修飾キー: cmd, alt, ctrl, shift

# 使用できるコマンド: https://nikitabobko.github.io/AeroSpace/commands

# この行のコメントを外すと、alt + enter でターミナルを開けます
# 詳細: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
alt-a = 'workspace A' # 不要なワークスペースのキー割り当ては設定から削除できます
alt-b = 'workspace B'
alt-c = 'workspace C'
alt-d = 'workspace D'
alt-e = 'workspace E'
alt-f = 'workspace F'
alt-g = 'workspace G'
alt-i = 'workspace I'
alt-m = 'workspace M'
alt-n = 'workspace N'
alt-o = 'workspace O'
alt-p = 'workspace P'
alt-q = 'workspace Q'
alt-r = 'workspace R'
alt-s = 'workspace S'
alt-t = 'workspace T'
alt-u = 'workspace U'
alt-v = 'workspace V'
alt-w = 'workspace W'
alt-x = 'workspace X'
alt-y = 'workspace Y'
alt-z = 'workspace Z'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-f = 'move-node-to-workspace F'
alt-shift-g = 'move-node-to-workspace G'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-m = 'move-node-to-workspace M'
alt-shift-n = 'move-node-to-workspace N'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-r = 'move-node-to-workspace R'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-x = 'move-node-to-workspace X'
alt-shift-y = 'move-node-to-workspace Y'
alt-shift-z = 'move-node-to-workspace Z'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# 詳細: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# 詳細: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' バインドモードの宣言
# 詳細: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # レイアウトをリセット
#s = ['layout sticky tiling', 'mode main'] # sticky はまだサポートされていません https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # フローティングとタイル表示を切り替え
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']


[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace 2"
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace 4"
[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace 6"
